 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_3_1_EAVESDROPPING_ACCESS_TOKENS1" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Spoofing, Elevation of privileges, Information Disclosure in Auth server sending<br/>the access token to the client, Client requesting Authorization Server for the<br/>Access Token, Authorization server token endpoint
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.CONFIDENTIALITY" bgcolor="#EEEEEE"><font color="blue">CONFIDENTIALITY</font></td>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.INTEGRITY" bgcolor="#EEEEEE"><font color="blue">INTEGRITY</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_3_1_EAVESDROPPING_ACCESS_TOKENS1_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

Attackers may attempt to eavesdrop access tokens in transit from the<br/>authorization server to the client.
</td></tr>
   </table>>
    ]

"4_3_1_EAVESDROPPING_ACCESS_TOKENS1_attack" -> "4_3_1_EAVESDROPPING_ACCESS_TOKENS1"  [label = " exploits"]

    "4_3_1_EAVESDROPPING_ACCESS_TOKENS1_countermeasure0" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Secure transport layer to CLient to AUTH_SERVER by TLS
</td></tr>
   </table>>
   ]

     "4_3_1_EAVESDROPPING_ACCESS_TOKENS1_countermeasure0" -> "4_3_1_EAVESDROPPING_ACCESS_TOKENS1_attack" [label = " mitigates"]

    "4_3_1_EAVESDROPPING_ACCESS_TOKENS1_countermeasure1" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Limiting the scope of access tokens obtained through automated approvals
</td></tr>
   </table>>
   ]

     "4_3_1_EAVESDROPPING_ACCESS_TOKENS1_countermeasure1" -> "4_3_1_EAVESDROPPING_ACCESS_TOKENS1_attack" [label = " mitigates"]

}
@enduml

