 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_4_1_13_CODE_SUBSTITUTION" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

DoS Using Manufactured Authorization &quot;codes&quot;
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.CONFIDENTIALITY" bgcolor="#EEEEEE"><font color="blue">CONFIDENTIALITY</font></td>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.INTEGRITY" bgcolor="#EEEEEE"><font color="blue">INTEGRITY</font></td>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.NON_REPUDIATION" bgcolor="#EEEEEE"><font color="blue">NON_REPUDIATION</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_4_1_13_CODE_SUBSTITUTION_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

An attacker could attempt to log into an application or web site  using a<br/>victim’s identity. Applications relying on identity data  provided by an OAuth<br/>protected service API to login users are  vulnerable to this threat. This<br/>pattern can be found in so-called  &quot;social login&quot; scenarios.  As a<br/>prerequisite, [...]
</td></tr>
   </table>>
    ]

"4_4_1_13_CODE_SUBSTITUTION_attack" -> "4_4_1_13_CODE_SUBSTITUTION"  [label = " exploits"]

    "4_4_1_13_CODE_SUBSTITUTION_countermeasure0" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Clients indicate their ids in requests
</td></tr>
   </table>>
   ]

     "4_4_1_13_CODE_SUBSTITUTION_countermeasure0" -> "4_4_1_13_CODE_SUBSTITUTION_attack" [label = " mitigates"]

    "4_4_1_13_CODE_SUBSTITUTION_countermeasure1" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Secure User Login Protocol
</td></tr>
   </table>>
   ]

     "4_4_1_13_CODE_SUBSTITUTION_countermeasure1" -> "4_4_1_13_CODE_SUBSTITUTION_attack" [label = " mitigates"]

}
@enduml

