 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_4_1_3_AUTH_CODE_BRUTE_FORCE" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Spoofing, Elevation of privileges, Information Disclosure in: credential<br/>Authorization Grant
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.CONFIDENTIALITY" bgcolor="#EEEEEE"><font color="blue">CONFIDENTIALITY</font></td>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.INTEGRITY" bgcolor="#EEEEEE"><font color="blue">INTEGRITY</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_4_1_3_AUTH_CODE_BRUTE_FORCE_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

An attacker may try to guess valid authorization &quot;code&quot; values and<br/>send the guessed code value using the grant type &quot;code&quot; in order to<br/>obtain a valid access token.
</td></tr>
   </table>>
    ]

"4_4_1_3_AUTH_CODE_BRUTE_FORCE_attack" -> "4_4_1_3_AUTH_CODE_BRUTE_FORCE"  [label = " exploits"]

    "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure0" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Use High Entropy for Secrets
</td></tr>
   </table>>
   ]

     "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure0" -> "4_4_1_3_AUTH_CODE_BRUTE_FORCE_attack" [label = " mitigates"]

    "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure1" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Sign Self-Contained Tokens
</td></tr>
   </table>>
   ]

     "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure1" -> "4_4_1_3_AUTH_CODE_BRUTE_FORCE_attack" [label = " mitigates"]

    "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure2" [ 
       fillcolor="#D5E8D4", style=filled, shape=polygon, color="#82B366", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Issue Installation-Specific Client Secrets
</td></tr>
   </table>>
   ]

     "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure2" -> "4_4_1_3_AUTH_CODE_BRUTE_FORCE_attack" [label = " mitigates"]

    "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure3" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Binding of Authorization &quot;code&quot; to &quot;redirect_uri&quot;
</td></tr>
   </table>>
   ]

     "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure3" -> "4_4_1_3_AUTH_CODE_BRUTE_FORCE_attack" [label = " mitigates"]

    "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure4" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Use Short Expiration Time
</td></tr>
   </table>>
   ]

     "4_4_1_3_AUTH_CODE_BRUTE_FORCE_countermeasure4" -> "4_4_1_3_AUTH_CODE_BRUTE_FORCE_attack" [label = " mitigates"]

}
@enduml

