 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_4_1_11_DOS_TOKEN_ENTROPY" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Denial of Service in: dataflow Auth User Agent Redirection
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.AVAILABILITY" bgcolor="#EEEEEE"><font color="blue">AVAILABILITY</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_4_1_11_DOS_TOKEN_ENTROPY_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

If an authorization server includes a nontrivial amount of entropy in<br/>authorization &quot;codes&quot; or access tokens (limiting the number of<br/>possible codes/tokens) and automatically grants either without user<br/>intervention and has no limit on codes or access tokens per user, an  attacker<br/>could exhaust the pool of[...]
</td></tr>
   </table>>
    ]

"4_4_1_11_DOS_TOKEN_ENTROPY_attack" -> "4_4_1_11_DOS_TOKEN_ENTROPY"  [label = " exploits"]

    "4_4_1_11_DOS_TOKEN_ENTROPY_countermeasure0" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Limit access tokens granted per user
</td></tr>
   </table>>
   ]

     "4_4_1_11_DOS_TOKEN_ENTROPY_countermeasure0" -> "4_4_1_11_DOS_TOKEN_ENTROPY_attack" [label = " mitigates"]

    "4_4_1_11_DOS_TOKEN_ENTROPY_countermeasure1" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

High entropy codes
</td></tr>
   </table>>
   ]

     "4_4_1_11_DOS_TOKEN_ENTROPY_countermeasure1" -> "4_4_1_11_DOS_TOKEN_ENTROPY_attack" [label = " mitigates"]

}
@enduml

