 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_4_2_1_TOKEN_LEAK1_NETWORK" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Access Token Leak in Transport/Endpoints
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.CONFIDENTIALITY" bgcolor="#EEEEEE"><font color="blue">CONFIDENTIALITY</font></td>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.INTEGRITY" bgcolor="#EEEEEE"><font color="blue">INTEGRITY</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_4_2_1_TOKEN_LEAK1_NETWORK_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

This token might be eavesdropped by an attacker. The token is sent from the<br/>server to the client via a URI fragment of the redirect URI. If the<br/>communication is not secured or the endpoint is not secured, the token could be<br/>leaked by parsing the returned URI.
</td></tr>
   </table>>
    ]

"4_4_2_1_TOKEN_LEAK1_NETWORK_attack" -> "4_4_2_1_TOKEN_LEAK1_NETWORK"  [label = " exploits"]

    "4_4_2_1_TOKEN_LEAK1_NETWORK_countermeasure0" [ 
       fillcolor="#D5E8D4", style=filled, shape=polygon, color="#82B366", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Ensure Confidentiality of Requests (TLS)
</td></tr>
   </table>>
   ]

     "4_4_2_1_TOKEN_LEAK1_NETWORK_countermeasure0" -> "4_4_2_1_TOKEN_LEAK1_NETWORK_attack" [label = " mitigates"]

}
@enduml

