 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Malicious Client Obtains Authorization
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.CONFIDENTIALITY" bgcolor="#EEEEEE"><font color="blue">CONFIDENTIALITY</font></td>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.INTEGRITY" bgcolor="#EEEEEE"><font color="blue">INTEGRITY</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

A malicious client could attempt to obtain a token by fraud.
</td></tr>
   </table>>
    ]

"4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_attack" -> "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY"  [label = " exploits"]

    "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure0" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Validate Pre-Registered &quot;redirect_uri&quot;
</td></tr>
   </table>>
   ]

     "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure0" -> "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_attack" [label = " mitigates"]

    "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure1" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Validation of Client Properties by End User
</td></tr>
   </table>>
   ]

     "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure1" -> "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_attack" [label = " mitigates"]

    "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure2" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Automatic Processing of Repeated Authorizations Requires Client Validation
</td></tr>
   </table>>
   ]

     "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure2" -> "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_attack" [label = " mitigates"]

    "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure3" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Automatic Processing of Repeated Authorizations Requires Client Validation
</td></tr>
   </table>>
   ]

     "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure3" -> "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_attack" [label = " mitigates"]

    "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure4" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Limit Token Scope
</td></tr>
   </table>>
   ]

     "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_countermeasure4" -> "4_4_2_2_TOKEN_LEAK2_BROWSER_HISTORY_attack" [label = " mitigates"]

}
@enduml

