 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_4_1_9_CLICKJACKING" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Clickjacking Attack against Authorization
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.CONFIDENTIALITY" bgcolor="#EEEEEE"><font color="blue">CONFIDENTIALITY</font></td>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.NON_REPUDIATION" bgcolor="#EEEEEE"><font color="blue">NON_REPUDIATION</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_4_1_9_CLICKJACKING_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

With clickjacking, a malicious site loads the target site in a transparent<br/>iFrame (see [iFrame]) overlaid on top of a set of dummy buttons that are<br/>carefully constructed to be placed directly under important buttons on the<br/>target site. When a user clicks a visible button, they are actually clicking a<br/>button[...]
</td></tr>
   </table>>
    ]

"4_4_1_9_CLICKJACKING_attack" -> "4_4_1_9_CLICKJACKING"  [label = " exploits"]

    "4_4_1_9_CLICKJACKING_countermeasure0" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Link the state Parameter to User Agent Session (anti CSRF)
</td></tr>
   </table>>
   ]

     "4_4_1_9_CLICKJACKING_countermeasure0" -> "4_4_1_9_CLICKJACKING_attack" [label = " mitigates"]

    "4_4_1_9_CLICKJACKING_countermeasure1" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

JavaScript frame-busting
</td></tr>
   </table>>
   ]

     "4_4_1_9_CLICKJACKING_countermeasure1" -> "4_4_1_9_CLICKJACKING_attack" [label = " mitigates"]

}
@enduml

