 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "4_4_1_12_DOS2" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Denial of Service in Authorization server
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.AVAILABILITY" bgcolor="#EEEEEE"><font color="blue">AVAILABILITY</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"4_4_1_12_DOS2_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

An attacker who owns a botnet can locate the redirect URIs of clients  that<br/>listen on HTTP, access them with random authorization &quot;codes&quot;,  and<br/>cause a large number of HTTPS connections to be concentrated onto  the<br/>authorization server. This can result in a denial-of-service  (DoS) attack on<br/>the authorizati[...]
</td></tr>
   </table>>
    ]

"4_4_1_12_DOS2_attack" -> "4_4_1_12_DOS2"  [label = " exploits"]

    "4_4_1_12_DOS2_countermeasure0" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Link the state Parameter to User Agent Session (anti CSRF)
</td></tr>
   </table>>
   ]

     "4_4_1_12_DOS2_countermeasure0" -> "4_4_1_12_DOS2_attack" [label = " mitigates"]

    "4_4_1_12_DOS2_countermeasure1" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Client limits authenticated users codes
</td></tr>
   </table>>
   ]

     "4_4_1_12_DOS2_countermeasure1" -> "4_4_1_12_DOS2_attack" [label = " mitigates"]

    "4_4_1_12_DOS2_countermeasure2" [ 
       fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Client limits authenticated users codes
</td></tr>
   </table>>
   ]

     "4_4_1_12_DOS2_countermeasure2" -> "4_4_1_12_DOS2_attack" [label = " mitigates"]

}
@enduml

