 

@startuml
digraph G {
rankdir="BT";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    "AuthServerPhishing1" [ fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450"
    label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Threat</b><br/> 

Spoofing, Elevation of privileges, Information Disclosure
</td></tr>
     <tr><td><table border="0" cellborder="0" cellspacing="8"><tr>
                ret += secObj.linkedImpactMDText()
     <td align="center" href="#OAuth2.CONFIDENTIALITY" bgcolor="#EEEEEE"><font color="blue">CONFIDENTIALITY</font></td>
     </tr></table></td></tr>   
   </table>>
   ];
    
"AuthServerPhishing1_attack" [ fillcolor="#f5f5f5", style=filled, shape=polygon, color="#666666", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Attack</b><br/>

A hostile party could take advantage of this by intercepting the client&#x27;s<br/>requests and returning misleading or otherwise incorrect responses.  This could<br/>be achieved using DNS or Address Resolution Protocol (ARP) spoofing.  Wide<br/>deployment of OAuth and similar protocols may cause users to become inured to<br/>t[...]
</td></tr>
   </table>>
    ]

"AuthServerPhishing1_attack" -> "AuthServerPhishing1"  [label = " exploits"]

    "AuthServerPhishing1_countermeasure0" [ 
       fillcolor="#D5E8D4", style=filled, shape=polygon, color="#82B366", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

TLS for the authorization server
</td></tr>
   </table>>
   ]

     "AuthServerPhishing1_countermeasure0" -> "AuthServerPhishing1_attack" [label = " mitigates"]

    "AuthServerPhishing1_countermeasure1" [ 
       fillcolor="#D5E8D4", style=filled, shape=polygon, color="#82B366", label =     
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="left"><b>Countermeasure</b><br/> 

Users educated to avoid phishing attacks
</td></tr>
   </table>>
   ]

     "AuthServerPhishing1_countermeasure1" -> "AuthServerPhishing1_attack" [label = " mitigates"]

}
@enduml

