







@startuml
digraph G {
rankdir="RL";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    
AVAILABILITY [fillcolor="#bae9ff", style=filled shape=ellipse, color="#2bbcff", label="AVAILABILITY", label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>AVAILABILITY</b><br/>

Ability to maintain fundamental availability of the system
</td></tr>
   </table>>]






}

@enduml