







@startuml
digraph G {
rankdir="RL";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    
CLIENT_REVOKE_ACCESS [fillcolor="#bae9ff", style=filled shape=ellipse, color="#2bbcff", label="CLIENT_REVOKE_ACCESS", label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>CLIENT_REVOKE_ACCESS</b><br/>

Revoke access to CLIENT over time
</td></tr>
   </table>>]






}

@enduml