







@startuml
digraph G {
rankdir="RL";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    
CLIENT_LIMIT_ACCESS [fillcolor="#bae9ff", style=filled shape=ellipse, color="#2bbcff", label="CLIENT_LIMIT_ACCESS", label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>CLIENT_LIMIT_ACCESS</b><br/>

Limit the set of resources accessed by CLIENT (authorization)
</td></tr>
   </table>>]






}

@enduml