







@startuml
digraph G {
rankdir="RL";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    
FULL_CIA [fillcolor="#bae9ff", style=filled shape=ellipse, color="#2bbcff", label="FULL_CIA", label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>FULL_CIA</b><br/>

Ability to maintain fundamental confidentiality integrity and availability of<br/>the system
</td></tr>
   </table>>]






}

@enduml