ID: Secrets
title: Kubernetes Secrets Security
version: 1.0
authors: |
  David Cervigni
parent: Kubernetes
scope:
  description: |
    
    
    **NOTE:** this is an example if threat model created with by training an LLM


    This document extends the Kubernetes security model to focus on threats specific to the handling,
     storage, and access of Kubernetes secrets. It includes detailed threats and mitigations to
      ensure the confidentiality, integrity, and secure management of secrets.
     
  securityObjectives:
    - ID: SECRET_CONFIDENTIALITY
      title: Secrets Confidentiality
      description: |
        Ensure Kubernetes secrets are protected from unauthorized access both in transit and at rest.
      group: Data Security

    - ID: SECRET_INTEGRITY
      title: Secrets Integrity
      description: |
        Prevent unauthorized modification of Kubernetes secrets to maintain their integrity.
      group: System Integrity

    - ID: ACCESS_CONTROL
      title: Access Control for Secrets
      description: |
        Restrict access to secrets based on the principle of least privilege.
      group: Access Management

    - ID: AUDITABILITY
      title: Secrets Auditability
      description: |
        Ensure all access to and modifications of secrets are auditable and logged for accountability.
      group: Monitoring and Audit

  assumptions:
    - ID: CLUSTER_EXPOSURE
      description: |
        The Kubernetes cluster may be exposed to external networks, increasing the risk of unauthorized access.
    - ID: NODE_COMPROMISE
      description: |
        Individual cluster nodes or workloads may be compromised by attackers, potentially exposing stored secrets.

  attackers:
    - ID: MALICIOUS_USER
      description: |
        Authorized users who attempt to misuse their access to secrets for malicious purposes.
      inScope: true
    - ID: EXTERNAL_ATTACKER
      description: |
        Unauthorized external entities attempting to access secrets through exposed APIs or workloads.
      inScope: true
    - ID: COMPROMISED_WORKLOAD
      description: |
        A compromised container or workload attempting to read or modify secrets it has access to.
      inScope: true

analysis: |
  While encryption of secrets at rest provides a layer of defense, it is not a
        complete solution since an attacker who gains access to etcd or the API server can often retrieve
         secrets at runtime.
threats:
  - ID: UNAUTHORIZED_SECRET_ACCESS
    title: Unauthorized Access to Secrets
    threatType: Information Disclosure
    impactDesc: |
      Exposure of sensitive information, such as credentials or API keys, stored as Kubernetes secrets.
    attack: |
      Attackers exploit overly permissive access controls or stolen credentials to access secrets.
    impactedSecObj:
      - REFID: SECRET_CONFIDENTIALITY
    attackers:
      - REFID: EXTERNAL_ATTACKER
      - REFID: MALICIOUS_USER
    countermeasures:
      - ID: RBAC_FOR_SECRETS
        title: Enforce RBAC for Secrets
        description: |
          Apply strict Role-Based Access Control (RBAC) policies to ensure only authorized entities can access specific secrets.
        inPlace: true
        public: true

    CVSS:
      base: TODO CVSS
      vector: ''
    fullyMitigated: false
  - ID: SECRET_INJECTION
    title: Secret Injection or Tampering
    threatType: Tampering
    impactDesc: |
      Modification of secrets to introduce malicious values, potentially compromising applications relying on them.
    attack: |
      A malicious user or workload tampers with secrets through improperly secured API access.
    impactedSecObj:
      - REFID: SECRET_INTEGRITY
    attackers:
      - REFID: MALICIOUS_USER
      - REFID: COMPROMISED_WORKLOAD
    countermeasures:
      - ID: AUDIT_SECRET_ACCESS
        title: Audit Secret Access and Modifications
        description: |
          Enable audit logs for all API interactions with secrets to detect and investigate unauthorized modifications.
        inPlace: true
        public: true

    CVSS:
      base: TODO CVSS
      vector: ''
    fullyMitigated: false
  - ID: NODE_STORAGE_EXPOSURE
    title: Secrets Exposure on Compromised Nodes
    threatType: Information Disclosure
    impactDesc: |
      Secrets stored on a compromised node are exposed, potentially leading to cluster-wide compromise.
    attack: |
      Attackers extract secrets directly from node storage or memory, bypassing API server protections.
    impactedSecObj:
      - REFID: SECRET_CONFIDENTIALITY
    attackers:
      - REFID: EXTERNAL_ATTACKER
      - REFID: COMPROMISED_WORKLOAD
    countermeasures:
      - ID: ENCRYPT_SECRETS_AT_REST
        title: Encrypt Secrets at Rest
        description: |
          Use Kubernetes encryption providers to ensure secrets stored on disk are encrypted with strong encryption standards. Note that encryption at rest does not mitigate runtime access vulnerabilities; additional runtime protections are needed.
        inPlace: true
        public: true

    CVSS:
      base: TODO CVSS
      vector: ''
    fullyMitigated: false
  - ID: SECRETS_IN_TRANSIT
    title: Secrets Intercepted in Transit
    threatType: Information Disclosure
    impactDesc: |
      Secrets transmitted over the network are intercepted, leading to potential exposure of sensitive data.
    attack: |
      Attackers intercept API server or etcd communication to extract secrets during transmission.
    impactedSecObj:
      - REFID: SECRET_CONFIDENTIALITY
    attackers:
      - REFID: EXTERNAL_ATTACKER
    countermeasures:
      - ID: ENCRYPT_SECRETS_IN_TRANSIT
        title: Encrypt Secrets in Transit
        description: |
          Enforce TLS encryption for all communications involving secrets, including API server and etcd interactions.
        inPlace: true
        public: true

    CVSS:
      base: TODO CVSS
      vector: ''
    fullyMitigated: false
  - ID: EXCESSIVE_SECRET_ACCESS
    title: Excessive Permissions for Secrets
    threatType: Elevation of Privilege
    impactDesc: |
      Unauthorized access or misuse of secrets due to overly broad permissions granted to workloads or users.
    attack: |
      Attackers leverage misconfigured RBAC policies or service account bindings to access secrets beyond their intended scope.
    impactedSecObj:
      - REFID: ACCESS_CONTROL
    attackers:
      - REFID: MALICIOUS_USER
      - REFID: COMPROMISED_WORKLOAD
    countermeasures:
      - ID: LEAST_PRIVILEGE_ACCESS
        title: Enforce Least Privilege Access
        description: |
          Audit and enforce least privilege access to secrets, ensuring users and workloads have access only to what they require.
        inPlace: false
        public: true
    CVSS:
      base: TODO CVSS
      vector: ''
    fullyMitigated: false
