







@startuml
digraph G {
rankdir="RL";
  node [shape=plaintext, fontname="Arial" fontsize="12"];
    
"CLIENT_ACCESS_LIMITATION" [fillcolor="#bae9ff", style=filled shape=ellipse, color="#2bbcff", label="CLIENT_ACCESS_LIMITATION", label= 
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>CLIENT_ACCESS_LIMITATION</b><br/>

Limits CLIENT access to RESOURCE_OWNER&#x27;s assets and data . This includes:<br/>Revoke access to CLIENT over time Limit the set of resources accessed by CLIENT<br/>(authorization)
</td></tr>
   </table>>]






}

@enduml