name: Publish MKDocs Site

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/corda/threat-model-tool


      - name: Build site
        run: |
          python -m r3threatmodeling.fullBuildDirectory \
            --TMDirectory threatModels \
            --outputDir build/docs \
            --template TM_templateMKDOCS \
            --formatYAML \
            --assetDir threatModels/assets \
            --templateSiteFolderSRC scripts/mkdocs \
            --templateSiteFolderDST build \
            --MKDocsSiteDir public \
            --MKDocsDir build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/public

  deploy:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1